### ISSUE TITLE
Generated data

### ISSUE THREAD

**Issue by tghaleb** [ChessAnalysis/chess-analysis-database#1]
Hello. Very interesting project. I see some sample csv files under the resources directory, is the rest of the data available for download somewhere?

**Comment by ghost** [comment]
Hi,

You should ask to Mathieu Acher. He was our tutor for this project.
http://mathieuacher.com/

Our university ran servers for a whole summer to generate data about chess
games.

2016-05-19 4:43 GMT+02:00 tghaleb notifications@github.com:

**Comment by tghaleb** [comment]
Thanks, I will try to contact him, then.

Do I understand from what you're saying that the project is already finished, or do you still plan to do more work on the collected data and/or generate more data?

**Comment by ghost** [comment]
This project was only a school assignment for us.
Mathieu will answer your questions better than me :)

2016-05-20 18:22 GMT+02:00 tghaleb notifications@github.com:

**Comment by tghaleb** [comment]
I see :-) Thanks.
